# Mission Overview {#mission-overview}

## Background

As part of a collaborative agreement between Fisheries and Oceans Canada (DFO), Natural Resources of Canada (NRCan), and the University of Rhode Island, U.S.A, the Research Vessel (RV) _Endeavor_ was used to deliver DFO's Maritimes Region Atlantic Zone Monitoring Program's (AZMP) 2025 spring survey of the Scotian Shelf and Gulf of Maine. The AZMP was initiated in 1998 with the aim to detect, track, and predict changes in the state and productivity of waters across the northwest Atlantic. The AZMP’s sampling strategy in the Maritimes Region is based on high-frequency (weekly, biweekly, monthly) data collection, hydrographic data collection on the winter and summer Ecosystem Trawl Surveys, and dedicated oceanographic surveys conducted each spring and fall. During the EN728 mission, data and sample collection was conducted across a network of fixed monitoring stations spanning from the Gulf of Maine and the Northeast Channel in the west, and across the Scotian Shelf to the Cabot Strait in the east, and included CTD-Rosette deployments for the collection of vertical profile data and water samples for nutrient, salinity, dissolved oxygen, and chlorophyll _a_ determination, ocean acidification and phytoplankton monitoring, and vertical ring net tows for the collection of data on zooplankton abundance and biomass. 

The RV _Endeavor_ is owned by the U.S. National Science Foundation (NSF) and operated under a Charter Party Agreement by the University of Rhode Island (URI) Graduate School of Oceanography to support multidisciplinary oceanographic missions led by both US scientists and the international community. Built in 1975, this 55-metre long vessel contains three lab spaces for science use, a science network for data sharing and access, two overboarding frames on its main deck, the starboard-side J-frame with two winches spooled with 0.322" electromechanical cable to support CTD-Rosette deployments, and a stern A-frame. The vessel's home port is 215 South Ferry Road, GSO, University of Rhode Island, Narragansett, RI, and missions are scheduled by the University-National Oceanographic Laboratory System (UNOLS) Ship Scheduling Committee. The RV _Endeavor_ was previously chartered by DFO in 2017 to deliver the program's fall mission in the Maritimes Region (mission ID EN606).

In addition to the EN728 mission's primary objectives in support of the Maritimes Region AZMP, data and samples were also collected in support of other research and monitoring programs and initiatives led by both DFO and its external partners, including university projects aimed at evaluating aspects of the marine environment (e.g., microbial component) not monitored by DFO (see the [Mission Achievements](#mission-achievements) section below for more details). 

This report provides an overview of the mission objectives, achievements and impacts, and a summary of operations and data collected.



## Mission Synopsis

The RV _Endeavor_ departed Narragansett, RI on the morning of Monday March 24, 2025 and began its transit to Nova Scotia for the start of the EN728 mission. The transit took over 48 hours, with the vessel meeting the Halifax harbour pilot at 13:30 ADT on Wednesday March 26. Upon arrival, the _Endeavor_ berthed along the south side of the Bedford Institute of Oceanography's finger pier, where it remained for mobilization. On Thursday March 27, mobilization of science equipment for the EN728 mission began at 08:00 ADT. A series of steel cages with equipment were brought over to the vessel and loaded onto its main deck using the vessel's knuckleboom crane. The remainder of the day was spent dispersing and setting up various laboratory equipment to the Main, Special Purpose, and Wet laboratories on board.

On Friday March 28, a familiarization meeting was held at 10:30 ADT with URI marine technicians Claire Mayorga and Lynne Butler to review the safety procedures and expectations for scientific operations. Afterwards, the remaining scientific and mooring equipment was loaded on the vessel, and mobilization was completed that afternoon. 

After mobilization was completed, chief scientist Lindsay Beazley reviewed the upcoming weather forecasted for the first few days of the mission. A storm was forecasted to impact the Scotian Shelf starting on Monday, March 31, which would cause high winds and seas that would last until Wednesday April 2. In light of this, a decision was made to alter the mission itinerary to facilitate the deployment of a large passive acoustic monitoring (PAM) mooring in Roseway Basin before arrival of the storm. Instead of heading towards Yarmouth Line, the itinerary was revised so that the AZMP's core Browns Bank Line would be occupied first, with deployment of the PAM mooring occurring in between stations BBL_02 and BBL_03. This would ensure the PAM mooring was deployed during safety operating conditions.

On Saturday, March 29, all science staff boarded the vessel for 08:00. A ship's familiarization meeting was held with the second officer to review safe operating procedures and drill protocols. At the same time, the RV _Endeavor_ prepared for departure, and left the BIO pier at 09:30 ADT after boarding the Halifax Port authority pilot. After transiting through the Halifax Harbour and disembarking the pilot, the vessel headed towards the first station of the mission, the AZMP's high-frequency station Halifax-2 located 30 nm outside the Halifax Harbour. Operations at this station began with a CTD-Rosette deployment, followed by two vertical ring net tows and a secchi disc deployment. After completion of these activities, a decision was made to change the order of operations for all stations going forward so that the vertical ring net tow was completed first and the CTD-Rosette deployment second. This allowed for sampling of the rosette to occur during the transit between stations, and provided unimpeded deck space to safely recover the net and deployment weight.

Upon completion of activities at HL_02, the RV _Endeavor_ proceeded towards the AZMP's Browns Bank Line, where AZMP stations BBL_01 and BBL_02 were sampled prior to arrival at the PAM mooring station in Roseway Basin (station ROPB) at ~ 11:45 UTC, Sunday March 30. Deployment of the mooring was finished by 13:00 UTC, and the vessel continued towards the remaining stations on the Browns Bank Line. After completion of the final station on this line, BBL_07, Monday March 31, the _Endeavor_ headed north towards the start of the Yarmouth Line, which was expected to be more sheltered from the pending storm. Upon arrival at YL_01, conditions were deemed operable, and deployment of the ring net occurred at ~ 19:00 UTC that same day. Conditions remained favourable to continue and complete operations along the Yarmouth Line. Following this, the Portsmouth Line was occupied, followed by the 10 stations of the Northeast Channel Line. The sea state remained high while in this area, resulting in challenging working conditions while sampling on deck and deploying ring nets. On several stations, the ring net crossbow slid down the wire, resulting in aborted operations and a re-deployment of equipment.

Upon completion of the Northeast Channel Line, the vessel proceeded towards the first station on the Halifax Line, HL_01, arriving at ~22:30 UTC on April 4. Over the course of nearly two days, all stations on the Halifax Line were successfully completed, with the first Argo float deployment of the mission occurring on station HL_07 after completion of ring net and CTD-Rosette operations on Sunday April 6 at ~12:00 UTC. Upon completion of the Halifax Line, the vessel proceeded to the next work location, The Gully Marine Protected Area (MPA), where an array of 15 Ocean Tracking Network (OTN) acoustic receiver moorings were planned for recovery. Deployed for approximately 4 years, these moorings were part of a DFO-OTN project to evaluate the movement of tagged species, particularly juvenile Atlantic halibut, in and around the MPA. During the transit to The Gully, the Captain and chief scientist reviewed the upcoming weather conditions for the week, and noted the development of a significant storm that would impact the Sable Island Bank area on the evening of Tuesday April 8 into Wednesday April 9. Consequently, the chief scientist planned to sample as many AZMP CTD-Rosette/ring net stations as possible during the overnight hours of Sunday April 6 to Monday April 7, and position the vessel on the first mooring station, GUL01, at daylight on Monday, April 7. 

The vessel arrived AZMP station GUL_04 at ~03:30 UTC on Monday April 7. As sampling from the rosette took longer than anticipated, a decision was made not to sample a second AZMP CTD station, and head to the first mooring station. The vessel arrived at mooring station GUL01 at ~ 11:30 UTC on Monday April 7. Communications were quickly established with the mooring and it was released. The mooring assembly was recovered using the vessel's knuckleboom crane, and the vessel proceeded to the next mooring station, GUL02. After communications were established with the mooring at GUL02 and the command sent to release it, the mooring failed to surface. The health status of the mooring release was evaluated, which indicated a release tilt ranging between 56 and 68$^\circ$, suggesting the release was not vertical in the water column. Consequently, the mooring at this station could not be recovered. The mooring at GUL03 also did not surface after release, and its tilt status was also higher than expected (68-79$^\circ$). The vessel moved on to the remaining moorings (stations GUL04 through GUL15). Communications could not be established with the releases at GUL05 and GUL12. Upon recovering the mooring at the last station of the array (GUL15), the vessel returned to the AZMP stations situated over the thalweg of the Gully, and completed these overnight on April 7 - 8 while continuing to monitor weather conditions. On April 8, a second attempt was made to recover the moorings at stations GUL02, GUL03, GUL05, and GUL12. Communications could be established with GUL12 and it was successfully recovered, but the moorings at GUL02, GUL03, and GUL12 were not recovered. 

Upon departure from The Gully MPA, the weather conditions for the eastern Scotian Shelf and Laurentian Channel were reviewed by the chief scientist and Captain. A significant weather system was expected to impact the area, bringing with it significant winds (up to 35 knots) and seas (up to 4.5 m). A decision was made to transit towards the next work area, the Laurentian Channel Mouth (LCM) section, but with the expectation that conditions might not be favourable to conduct science operations. After the vessel arrived at station LCM_01 at midnight on April 9, the conditions were assessed and deemed unfavourable for science operations. The bridge positioned the vessel to provide the most comfort for those on board, and waited out the storm. Conditions improved enough to allow science operations to continue at 19:00 UTC on April 9. Overall, the storm resulted in a loss of 16 hours to the program. All 10 stations on the LCM line were completed successfully by 19:18 UTC on April 10, and the vessel moved on to its next section, the Louisbourg Line, arriving at LL_09 at 07:09 UTC on April 11. The second Argo float was deployed after ring net and CTD operations were completed at this station, and the vessel transited north, completing all remaining stations on the Louisbourg Line. Operations at the final station on the line were completed at 16:08 UTC on April 12, and the vessel proceeded to its next work area, the Cabot Strait.

Operations on the Cabot Strait Line (CSL) began at station CSL_01 located east of Cape Breton, at 00:21 UTC on April 13. Conditions while working in the area were favourable, and no ice was observed. The vessel worked from west to east, completing operations at station CSL_06 located off Port Aux Basque, Newfoundland, approximately 14 hours later at 14:12 UTC. The vessel then headed towards the last planned section, the St. Anns Bank (STAB) Line, and started at station STAB_06. Upon review of the final planned activities for the EN728 mission, it was evident that the planned program would be completed well in advance of the scheduled disembarkation on Saturday April 19. At this point, proposals for additional data collection were reviewed. A set of 7 stations located on the western side of Sable Island that were sampled in 2022 during the spring AZMP mission (AT4802) to evaluate the effects of potential seal fertilization on the water column were added to the program, as were 5 stations on the extended Halifax Line (HL_08 through HL_12). Operations at the final station on the St. Anns Bank Line were completed at 11:26 on Monday April 14, and the vessel proceeded towards Sable Island Bank. 

Operations at Sable Island Bank (SIB) station SIB_11 commenced at 22:37 UTC on Monday April 14. A review of sea surface chlorophyll _a_ from satellite imagery (E. Devred, personal communication) indicated high levels of chlorophyll in the area, suggesting the spring bloom was still occurring in the region. The resulting images from the Woods Hole Imaging Flow Cytobot (IFCB) suggested that the bloom was dominated by one species, a member of the genus _Leptocylindrus_, a long, cylindrical diatom. Operations on the 7th SIB station (SIB_02) were completed on Tuesday April 15 at 21:06, and the vessel proceeded towards the extended Halifax Line.

The chief scientist reviewed the upcoming weather conditions for the central Scotian Shelf with the Captain, and noted that a significant storm would potentially impact the central Scotian Shelf at the location of the extended Halifax Line. Consequently, a decision was made to start at station HL_08 and work south, completing as many stations on the extended Halifax Line as possible before conditions worsened. The vessel arrived at HL_08 at 02:33 UTC on April 16 and operations began with deployment of the 202 $\mu$m ring net, followed by a CTD-Rosette cast. Conditions began to worsen as the vessel transited south, and when at HL_11, a decision was made to cancel operations at the final station, HL_12 and transit back to port. Upon completion of the CTD-Rosette deployment at HL_11, the vessel departed the extended Halifax Line and transited north towards station HL_02, arriving at 23:45 UTC on Thursday April 17. Operations began with the deployment of the 202 and 76 $\mu$m ring net systems, followed by the CTD-Rosette. Once operations were completed, the vessel transited north towards the Halifax pilot station outside the mouth of Halifax Harbour. 

The pilot was scheduled for Friday April 18 at 08:30 AST, one day prior to the mission's scheduled disembarkation. After the pilot boarded, the vessel began its transit through the Halifax Harbour, and arrived at the BIO at ~ 10:00 local time. The vessel berthed along the south side of the BIO finger pier. Demobilization activities began at 12:30 AST. Wire baskets were craned onto the vessel using its knuckleboom crane and filled with science equipment, and transfered back onto the pier where they were forklifted into a storage bay at the BIO. Demobilization activities were completed at ~ 15:00 AST on Friday April 18, marking conclusion of the EN728 mission. 


\clearpage
